- hosts: all
  vars_files:
          - "{{ ansible_facts['distribution'] }}.yml"
  tasks:
          - name: Webserver installation
            package:
                    name: "{{package_name}}"
                    state: present
          - name: copying webpages
            copy:
               content: "This os is {{ ansible_distribution }}"
               dest: "/var/www/html/index.html"
          - name: service-start
            service:
                     name: "{{ service_name }}"
                     state: started
 


